### PR TITLE
Added 'unknown' to version if version cannot be obtained

### PR DESCRIPTION
**Pull request by williamhatcher**

### CODE REVIEW

**Comment by Zerthick** [comment]
This shouldn't ever really happen in production, but it is still good practice to include a default value.

**Comment by williamhatcher** [comment]
Try running the latest release.
It does not display the version, IIRC.

**Comment by Zerthick** [comment]
I won't display the version when running the plugin within the IDE as it gets inserted when the jar is built.

**Comment by williamhatcher** [comment]
Ah, okay.

**Pull request merged**
